server:
  port: 6360
  name: inner-geteway
management:
  security:
    enabled: false
spring:
  application:
    name: ${server.name}
  cloud:
    config:
      discovery:
        enabled: false
    inetutils:
      ignored-interfaces:
        - docker0 #忽略docker网卡
        - veth.*  #忽略veth桥接的网卡
eureka:
  instance:
    #使用IP注册
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registryFetchIntervalSeconds: 30
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
    healthcheck:
      enabled: true

#如果是JAR外部的 需要使用file:c:/这种形式
geteway:
    routeFile: file:/home/jkx-geteway-server-1.0.0/conf/route.yml
    whiteListFile: file:/home/jkx-geteway-server-1.0.0/conf/ip.txt
    #routeFile: file:c:/route.yml

logging:
     config: file:${soft.home}/conf/logback.xml
ribbon:
  eureka:
    enabled: false

zuul:
  host:
    maxTotalConnections: 500
